site_name: Citrix Hypervisor Supplemental Packs and the DDK Guide
site_description: Citrix Hypervisor Supplemental Packs and the DDK Guide
site_title: Developer Documentation
site_url: https://developer-docs.citrix.com/

copyright: 'Copyright &copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

theme:
  name: null
  custom_dir: devdocs-theme
  include_search_page: false
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: /media/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png
  
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta

nav:
- Introduction: index.md
- Getting Started: getting-started.md
- Building the example packs: building-example-packs.md
- Installing supplemental packs: installing-packs.md
- Producing driver RPMs: producing-rpms.md
- Creating a supplemental pack: creating-a-pack.md
- Rules and Guidelines: rules-and-guidelines.md
- Testing and Certification: testing-and-certification.md
- Additional Resources: additional-resources.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/
